
package com.optimaize.anythingworks.exampleproject.clientlib.soap.services.development.exceptionthrower.wsdl;

import com.optimaize.anythingworks.exampleproject.clientlib.soap.commonwsdl.AccessDeniedWebServiceException;
import com.optimaize.anythingworks.exampleproject.clientlib.soap.commonwsdl.InternalServerErrorWebServiceException;
import com.optimaize.anythingworks.exampleproject.clientlib.soap.commonwsdl.InvalidInputWebServiceException;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoapExceptionThrower", targetNamespace = "http://exceptionthrower.development.soap.services.server.exampleproject.anythingworks.optimaize.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapExceptionThrower {


    /**
     * 
     * @param apiKey
     * @return
     *     returns java.lang.String
     * @throws InternalServerErrorWebServiceException
     * @throws InvalidInputWebServiceException
     * @throws AccessDeniedWebServiceException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "throwAccessDeniedNoSuchAccount", targetNamespace = "http://exceptionthrower.development.soap.services.server.exampleproject.anythingworks.optimaize.com/", className = "com.optimaize.anythingworks.exampleproject.clientlib.soap.services.development.exceptionthrower.wsdl.ThrowAccessDeniedNoSuchAccount")
    @ResponseWrapper(localName = "throwAccessDeniedNoSuchAccountResponse", targetNamespace = "http://exceptionthrower.development.soap.services.server.exampleproject.anythingworks.optimaize.com/", className = "com.optimaize.anythingworks.exampleproject.clientlib.soap.services.development.exceptionthrower.wsdl.ThrowAccessDeniedNoSuchAccountResponse")
    @Action(input = "http://exceptionthrower.development.soap.services.server.exampleproject.anythingworks.optimaize.com/SoapExceptionThrower/throwAccessDeniedNoSuchAccountRequest", output = "http://exceptionthrower.development.soap.services.server.exampleproject.anythingworks.optimaize.com/SoapExceptionThrower/throwAccessDeniedNoSuchAccountResponse", fault = {
        @FaultAction(className = AccessDeniedWebServiceException.class, value = "http://exceptionthrower.development.soap.services.server.exampleproject.anythingworks.optimaize.com/SoapExceptionThrower/throwAccessDeniedNoSuchAccount/Fault/AccessDeniedWebServiceException"),
        @FaultAction(className = InvalidInputWebServiceException.class, value = "http://exceptionthrower.development.soap.services.server.exampleproject.anythingworks.optimaize.com/SoapExceptionThrower/throwAccessDeniedNoSuchAccount/Fault/InvalidInputWebServiceException"),
        @FaultAction(className = InternalServerErrorWebServiceException.class, value = "http://exceptionthrower.development.soap.services.server.exampleproject.anythingworks.optimaize.com/SoapExceptionThrower/throwAccessDeniedNoSuchAccount/Fault/InternalServerErrorWebServiceException")
    })
    public String throwAccessDeniedNoSuchAccount(
        @WebParam(name = "apiKey", targetNamespace = "")
        String apiKey)
        throws AccessDeniedWebServiceException, InternalServerErrorWebServiceException, InvalidInputWebServiceException
    ;

    /**
     * 
     * @param apiKey
     * @return
     *     returns java.lang.String
     * @throws InternalServerErrorWebServiceException
     * @throws InvalidInputWebServiceException
     * @throws AccessDeniedWebServiceException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "throwAccessDeniedRequestLimitExceeded", targetNamespace = "http://exceptionthrower.development.soap.services.server.exampleproject.anythingworks.optimaize.com/", className = "com.optimaize.anythingworks.exampleproject.clientlib.soap.services.development.exceptionthrower.wsdl.ThrowAccessDeniedRequestLimitExceeded")
    @ResponseWrapper(localName = "throwAccessDeniedRequestLimitExceededResponse", targetNamespace = "http://exceptionthrower.development.soap.services.server.exampleproject.anythingworks.optimaize.com/", className = "com.optimaize.anythingworks.exampleproject.clientlib.soap.services.development.exceptionthrower.wsdl.ThrowAccessDeniedRequestLimitExceededResponse")
    @Action(input = "http://exceptionthrower.development.soap.services.server.exampleproject.anythingworks.optimaize.com/SoapExceptionThrower/throwAccessDeniedRequestLimitExceededRequest", output = "http://exceptionthrower.development.soap.services.server.exampleproject.anythingworks.optimaize.com/SoapExceptionThrower/throwAccessDeniedRequestLimitExceededResponse", fault = {
        @FaultAction(className = AccessDeniedWebServiceException.class, value = "http://exceptionthrower.development.soap.services.server.exampleproject.anythingworks.optimaize.com/SoapExceptionThrower/throwAccessDeniedRequestLimitExceeded/Fault/AccessDeniedWebServiceException"),
        @FaultAction(className = InvalidInputWebServiceException.class, value = "http://exceptionthrower.development.soap.services.server.exampleproject.anythingworks.optimaize.com/SoapExceptionThrower/throwAccessDeniedRequestLimitExceeded/Fault/InvalidInputWebServiceException"),
        @FaultAction(className = InternalServerErrorWebServiceException.class, value = "http://exceptionthrower.development.soap.services.server.exampleproject.anythingworks.optimaize.com/SoapExceptionThrower/throwAccessDeniedRequestLimitExceeded/Fault/InternalServerErrorWebServiceException")
    })
    public String throwAccessDeniedRequestLimitExceeded(
        @WebParam(name = "apiKey", targetNamespace = "")
        String apiKey)
        throws AccessDeniedWebServiceException, InternalServerErrorWebServiceException, InvalidInputWebServiceException
    ;

    /**
     * 
     * @param apiKey
     * @return
     *     returns java.lang.String
     * @throws InternalServerErrorWebServiceException
     * @throws InvalidInputWebServiceException
     * @throws AccessDeniedWebServiceException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "throwAccessDeniedTooManyConcurrentRequests", targetNamespace = "http://exceptionthrower.development.soap.services.server.exampleproject.anythingworks.optimaize.com/", className = "com.optimaize.anythingworks.exampleproject.clientlib.soap.services.development.exceptionthrower.wsdl.ThrowAccessDeniedTooManyConcurrentRequests")
    @ResponseWrapper(localName = "throwAccessDeniedTooManyConcurrentRequestsResponse", targetNamespace = "http://exceptionthrower.development.soap.services.server.exampleproject.anythingworks.optimaize.com/", className = "com.optimaize.anythingworks.exampleproject.clientlib.soap.services.development.exceptionthrower.wsdl.ThrowAccessDeniedTooManyConcurrentRequestsResponse")
    @Action(input = "http://exceptionthrower.development.soap.services.server.exampleproject.anythingworks.optimaize.com/SoapExceptionThrower/throwAccessDeniedTooManyConcurrentRequestsRequest", output = "http://exceptionthrower.development.soap.services.server.exampleproject.anythingworks.optimaize.com/SoapExceptionThrower/throwAccessDeniedTooManyConcurrentRequestsResponse", fault = {
        @FaultAction(className = AccessDeniedWebServiceException.class, value = "http://exceptionthrower.development.soap.services.server.exampleproject.anythingworks.optimaize.com/SoapExceptionThrower/throwAccessDeniedTooManyConcurrentRequests/Fault/AccessDeniedWebServiceException"),
        @FaultAction(className = InvalidInputWebServiceException.class, value = "http://exceptionthrower.development.soap.services.server.exampleproject.anythingworks.optimaize.com/SoapExceptionThrower/throwAccessDeniedTooManyConcurrentRequests/Fault/InvalidInputWebServiceException"),
        @FaultAction(className = InternalServerErrorWebServiceException.class, value = "http://exceptionthrower.development.soap.services.server.exampleproject.anythingworks.optimaize.com/SoapExceptionThrower/throwAccessDeniedTooManyConcurrentRequests/Fault/InternalServerErrorWebServiceException")
    })
    public String throwAccessDeniedTooManyConcurrentRequests(
        @WebParam(name = "apiKey", targetNamespace = "")
        String apiKey)
        throws AccessDeniedWebServiceException, InternalServerErrorWebServiceException, InvalidInputWebServiceException
    ;

    /**
     * 
     * @param apiKey
     * @return
     *     returns java.lang.String
     * @throws InternalServerErrorWebServiceException
     * @throws InvalidInputWebServiceException
     * @throws AccessDeniedWebServiceException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "throwInternal", targetNamespace = "http://exceptionthrower.development.soap.services.server.exampleproject.anythingworks.optimaize.com/", className = "com.optimaize.anythingworks.exampleproject.clientlib.soap.services.development.exceptionthrower.wsdl.ThrowInternal")
    @ResponseWrapper(localName = "throwInternalResponse", targetNamespace = "http://exceptionthrower.development.soap.services.server.exampleproject.anythingworks.optimaize.com/", className = "com.optimaize.anythingworks.exampleproject.clientlib.soap.services.development.exceptionthrower.wsdl.ThrowInternalResponse")
    @Action(input = "http://exceptionthrower.development.soap.services.server.exampleproject.anythingworks.optimaize.com/SoapExceptionThrower/throwInternalRequest", output = "http://exceptionthrower.development.soap.services.server.exampleproject.anythingworks.optimaize.com/SoapExceptionThrower/throwInternalResponse", fault = {
        @FaultAction(className = AccessDeniedWebServiceException.class, value = "http://exceptionthrower.development.soap.services.server.exampleproject.anythingworks.optimaize.com/SoapExceptionThrower/throwInternal/Fault/AccessDeniedWebServiceException"),
        @FaultAction(className = InvalidInputWebServiceException.class, value = "http://exceptionthrower.development.soap.services.server.exampleproject.anythingworks.optimaize.com/SoapExceptionThrower/throwInternal/Fault/InvalidInputWebServiceException"),
        @FaultAction(className = InternalServerErrorWebServiceException.class, value = "http://exceptionthrower.development.soap.services.server.exampleproject.anythingworks.optimaize.com/SoapExceptionThrower/throwInternal/Fault/InternalServerErrorWebServiceException")
    })
    public String throwInternal(
        @WebParam(name = "apiKey", targetNamespace = "")
        String apiKey)
        throws AccessDeniedWebServiceException, InternalServerErrorWebServiceException, InvalidInputWebServiceException
    ;

    /**
     * 
     * @param apiKey
     * @return
     *     returns java.lang.String
     * @throws InternalServerErrorWebServiceException
     * @throws InvalidInputWebServiceException
     * @throws AccessDeniedWebServiceException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "throwInvalidInput", targetNamespace = "http://exceptionthrower.development.soap.services.server.exampleproject.anythingworks.optimaize.com/", className = "com.optimaize.anythingworks.exampleproject.clientlib.soap.services.development.exceptionthrower.wsdl.ThrowInvalidInput")
    @ResponseWrapper(localName = "throwInvalidInputResponse", targetNamespace = "http://exceptionthrower.development.soap.services.server.exampleproject.anythingworks.optimaize.com/", className = "com.optimaize.anythingworks.exampleproject.clientlib.soap.services.development.exceptionthrower.wsdl.ThrowInvalidInputResponse")
    @Action(input = "http://exceptionthrower.development.soap.services.server.exampleproject.anythingworks.optimaize.com/SoapExceptionThrower/throwInvalidInputRequest", output = "http://exceptionthrower.development.soap.services.server.exampleproject.anythingworks.optimaize.com/SoapExceptionThrower/throwInvalidInputResponse", fault = {
        @FaultAction(className = AccessDeniedWebServiceException.class, value = "http://exceptionthrower.development.soap.services.server.exampleproject.anythingworks.optimaize.com/SoapExceptionThrower/throwInvalidInput/Fault/AccessDeniedWebServiceException"),
        @FaultAction(className = InvalidInputWebServiceException.class, value = "http://exceptionthrower.development.soap.services.server.exampleproject.anythingworks.optimaize.com/SoapExceptionThrower/throwInvalidInput/Fault/InvalidInputWebServiceException"),
        @FaultAction(className = InternalServerErrorWebServiceException.class, value = "http://exceptionthrower.development.soap.services.server.exampleproject.anythingworks.optimaize.com/SoapExceptionThrower/throwInvalidInput/Fault/InternalServerErrorWebServiceException")
    })
    public String throwInvalidInput(
        @WebParam(name = "apiKey", targetNamespace = "")
        String apiKey)
        throws AccessDeniedWebServiceException, InternalServerErrorWebServiceException, InvalidInputWebServiceException
    ;

}
