
package com.optimaize.anythingworks.exampleproject.clientlib.soap.commonwsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "AccessDeniedWebServiceException", targetNamespace = "http://system.services.server.exampleproject.anythingworks.optimaize.com/")
public class AccessDeniedWebServiceException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FaultBean faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public AccessDeniedWebServiceException(String message, FaultBean faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public AccessDeniedWebServiceException(String message, FaultBean faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.optimaize.anythingworks.exampleproject.clientlib.services.system.exceptionthrower.wsdl.FaultBean
     */
    public FaultBean getFaultInfo() {
        return faultInfo;
    }

}
