
package com.optimaize.anythingworks.exampleproject.clientlib.soap.commonwsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 *
 */
@WebFault(name = "SoapWebServiceException", targetNamespace = "http://exceptionthrower.development.soap.services.server.exampleproject.anythingworks.optimaize.com/")
public class SoapWebServiceException
        extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     *
     */
    private FaultBean faultInfo;

    /**
     *
     * @param message
     * @param faultInfo
     */
    public SoapWebServiceException(String message, FaultBean faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @param message
     * @param faultInfo
     * @param cause
     */
    public SoapWebServiceException(String message, FaultBean faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @return
     *     returns fault bean: com.optimaize.anythingworks.exampleproject.clientlib.soap.services.development.exceptionthrower.wsdl.FaultBean
     */
    public FaultBean getFaultInfo() {
        return faultInfo;
    }

}
