
package com.optimaize.soapworks.exampleproject.clientlib.services.system.ping.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoapPingService", targetNamespace = "http://system.services.server.userland.demosoapserver.optimaize.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapPingService {


    /**
     * 
     * @param apiKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ping", targetNamespace = "http://system.services.server.userland.demosoapserver.optimaize.com/", className = "com.optimaize.demosoapserver.userland.client.services.system.ping.wsdl.Ping")
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://system.services.server.userland.demosoapserver.optimaize.com/", className = "com.optimaize.demosoapserver.userland.client.services.system.ping.wsdl.PingResponse")
    @Action(input = "http://system.services.server.userland.demosoapserver.optimaize.com/SoapPingService/pingRequest", output = "http://system.services.server.userland.demosoapserver.optimaize.com/SoapPingService/pingResponse")
    public String ping(
            @WebParam(name = "apiKey", targetNamespace = "")
            String apiKey);

}
