
package com.optimaize.soapworks.exampleproject.clientlib.soap.services.development.requestinfo.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapRequestInfoServiceService", targetNamespace = "http://requestinfo.development.soap.services.server.exampleproject.soapworks.optimaize.com/", wsdlLocation = "http://localhost:80/soap/v1/system/requestinfo?wsdl")
public class SoapRequestInfoServiceService
    extends Service
{

    private final static URL SOAPREQUESTINFOSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPREQUESTINFOSERVICESERVICE_EXCEPTION;
    private final static QName SOAPREQUESTINFOSERVICESERVICE_QNAME = new QName("http://requestinfo.development.soap.services.server.exampleproject.soapworks.optimaize.com/", "SoapRequestInfoServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:80/soap/v1/system/requestinfo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPREQUESTINFOSERVICESERVICE_WSDL_LOCATION = url;
        SOAPREQUESTINFOSERVICESERVICE_EXCEPTION = e;
    }

    public SoapRequestInfoServiceService() {
        super(__getWsdlLocation(), SOAPREQUESTINFOSERVICESERVICE_QNAME);
    }

    public SoapRequestInfoServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPREQUESTINFOSERVICESERVICE_QNAME, features);
    }

    public SoapRequestInfoServiceService(URL wsdlLocation) {
        super(wsdlLocation, SOAPREQUESTINFOSERVICESERVICE_QNAME);
    }

    public SoapRequestInfoServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPREQUESTINFOSERVICESERVICE_QNAME, features);
    }

    public SoapRequestInfoServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapRequestInfoServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoapRequestInfoService
     */
    @WebEndpoint(name = "SoapRequestInfoServicePort")
    public SoapRequestInfoService getSoapRequestInfoServicePort() {
        return super.getPort(new QName("http://requestinfo.development.soap.services.server.exampleproject.soapworks.optimaize.com/", "SoapRequestInfoServicePort"), SoapRequestInfoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapRequestInfoService
     */
    @WebEndpoint(name = "SoapRequestInfoServicePort")
    public SoapRequestInfoService getSoapRequestInfoServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://requestinfo.development.soap.services.server.exampleproject.soapworks.optimaize.com/", "SoapRequestInfoServicePort"), SoapRequestInfoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPREQUESTINFOSERVICESERVICE_EXCEPTION!= null) {
            throw SOAPREQUESTINFOSERVICESERVICE_EXCEPTION;
        }
        return SOAPREQUESTINFOSERVICESERVICE_WSDL_LOCATION;
    }

}
