
package com.optimaize.soapworks.exampleproject.clientlib.services.system.requestinfo.wsdl;

import com.optimaize.soapworks.exampleproject.clientlib.commonwsdl.AccessDeniedWebServiceException;
import com.optimaize.soapworks.exampleproject.clientlib.commonwsdl.InternalServerErrorWebServiceException;
import com.optimaize.soapworks.exampleproject.clientlib.commonwsdl.InvalidInputWebServiceException;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoapRequestInfoService", targetNamespace = "http://system.services.server.exampleproject.soapworks.optimaize.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapRequestInfoService {


    /**
     * 
     * @param apiKey
     * @return
     *     returns java.lang.String
     * @throws InternalServerErrorWebServiceException
     * @throws AccessDeniedWebServiceException
     * @throws InvalidInputWebServiceException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "requestInfo", targetNamespace = "http://system.services.server.exampleproject.soapworks.optimaize.com/", className = "com.optimaize.soapworks.exampleproject.clientlib.services.system.requestinfo.wsdl.RequestInfo")
    @ResponseWrapper(localName = "requestInfoResponse", targetNamespace = "http://system.services.server.exampleproject.soapworks.optimaize.com/", className = "com.optimaize.soapworks.exampleproject.clientlib.services.system.requestinfo.wsdl.RequestInfoResponse")
    @Action(input = "http://system.services.server.exampleproject.soapworks.optimaize.com/SoapRequestInfoService/requestInfoRequest", output = "http://system.services.server.exampleproject.soapworks.optimaize.com/SoapRequestInfoService/requestInfoResponse", fault = {
        @FaultAction(className = AccessDeniedWebServiceException.class, value = "http://system.services.server.exampleproject.soapworks.optimaize.com/SoapRequestInfoService/requestInfo/Fault/AccessDeniedWebServiceException"),
        @FaultAction(className = InvalidInputWebServiceException.class, value = "http://system.services.server.exampleproject.soapworks.optimaize.com/SoapRequestInfoService/requestInfo/Fault/InvalidInputWebServiceException"),
        @FaultAction(className = InternalServerErrorWebServiceException.class, value = "http://system.services.server.exampleproject.soapworks.optimaize.com/SoapRequestInfoService/requestInfo/Fault/InternalServerErrorWebServiceException")
    })
    public String requestInfo(
        @WebParam(name = "apiKey", targetNamespace = "")
        String apiKey)
        throws AccessDeniedWebServiceException, InternalServerErrorWebServiceException, InvalidInputWebServiceException
    ;

}
